feat: create blog and providers section
llandkoer/Amecity pull request #5
Opened 2021-04-07 00:30 UTC by Jeferguto

Layout blog [US07](https://trello.com/c/2QqQg6Il/15-us7)
Layout providers screen [US28](https://trello.com/c/BWoIS9pK/36-us28)

2021-04-07 21:38 UTC, llandkoer requested changes
You did a very good job!  

Did you realize there is an empty file (`_providers.scss`) there? Is it necessary to be added?

2021-04-08 02:54 UTC, Jeferguto commented
I see. My styles weren't saved in that file. I will fix it and I will commit that change.

2021-04-08 17:17 UTC, NataliaOrtizMa reviewed
Remember to use the flex mixin, for example in `_blog-desktop.scss` file

2021-04-08 17:17 UTC, NataliaOrtizMa commented on src/layout/providers.html
> +    <section class="insumos">
Remember, the name of classes in English.

2021-04-26 15:52 UTC, NataliaOrtizMa commented on src/layout/blog-static.html
> +    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
Just a question, what are this scripts for?

2021-04-26 15:53 UTC, NataliaOrtizMa approved these changes
Nice job!

2021-04-26 16:04 UTC, llandkoer approved these changes
Good job!

2021-04-26 22:44 UTC, Jeferguto commented on src/layout/blog-static.html
> +    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
It is a source library that uses bootstrap, I am using them for the DROPDOWNS functionality of "filtrar" and "ordenar".

It will also help us to manipulate the DOM and it could be useful when we work JS.

2021-05-15 18:13 UTC, merged